"""add otp verification and operator application tables

Revision ID: 174ecee9a97f
Revises: 3e737e6c5f9b
Create Date: 2025-11-25 20:43:20.676042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '174ecee9a97f'
down_revision: Union[str, Sequence[str], None] = '3e737e6c5f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('office_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_office_invites_token'), 'office_invites', type_='unique')
    op.drop_index(op.f('ix_office_invites_token'), table_name='office_invites')
    op.create_index(op.f('ix_office_invites_token'), 'office_invites', ['token'], unique=True)
    op.alter_column('offices', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('offices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_offices_email'), 'offices', type_='unique')
    op.drop_index(op.f('ix_offices_email'), table_name='offices')
    op.create_index(op.f('ix_offices_email'), 'offices', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offices_email'), table_name='offices')
    op.create_index(op.f('ix_offices_email'), 'offices', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_offices_email'), 'offices', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('offices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('offices', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_office_invites_token'), table_name='office_invites')
    op.create_index(op.f('ix_office_invites_token'), 'office_invites', ['token'], unique=False)
    op.create_unique_constraint(op.f('uq_office_invites_token'), 'office_invites', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('office_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
