"""update_booking_with_passenger_details

Revision ID: ee7d1f8dd8d9
Revises: 5a4f56644434
Create Date: 2025-11-17 14:25:08.127814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7d1f8dd8d9'
down_revision: Union[str, Sequence[str], None] = '5a4f56644434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('passenger_title', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('passenger_first_name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('passenger_middle_name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('passenger_last_name', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('passenger_dob', sa.Date(), nullable=True))
    op.add_column('bookings', sa.Column('passenger_nationality', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('passenger_document_type', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('passenger_document_number', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('contact_address', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('contact_city', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('contact_country', sa.String(), nullable=True))
    op.drop_column('bookings', 'contact_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'contact_country')
    op.drop_column('bookings', 'contact_city')
    op.drop_column('bookings', 'contact_address')
    op.drop_column('bookings', 'passenger_document_number')
    op.drop_column('bookings', 'passenger_document_type')
    op.drop_column('bookings', 'passenger_nationality')
    op.drop_column('bookings', 'passenger_dob')
    op.drop_column('bookings', 'passenger_last_name')
    op.drop_column('bookings', 'passenger_middle_name')
    op.drop_column('bookings', 'passenger_first_name')
    op.drop_column('bookings', 'passenger_title')
    # ### end Alembic commands ###
